[workspace]
resolver = "2"
members = ["crates/rewriter", "crates/wisp-wasm", "crates/zeolite-server", "crates/wisp-core", "crates/wisp-extensions"]

[workspace.package]
version = "3.0.0"
edition = "2021"
license = "AGPL-3.0-only"

[workspace.dependencies]
wisp-core = { path = "crates/wisp-core" }
wisp-extensions = { path = "crates/wisp-extensions" }
wasm-bindgen = "0.2"
bytes = "1"
thiserror = "1"
sha2 = "0.10"
ed25519-dalek = "2"
rand = "0.8"
subtle = "2"

[profile.release]
opt-level = "z"
lto = true
